#include "stubs_asm.h"

//NHSTUB(SleepTask, 0xFFC196d0)
NHSTUB(CreateTask, 0xFF81E83C)    // OK
NHSTUB(ExitTask, 0xFF81EACC)    // OK
NHSTUB(AllocateMemory, 0xFFAB8CF0)

NHSTUB(EnterToCompensationEVF, 0xFFC00958)    // ToDo: nullsub_1
NHSTUB(ExitFromCompensationEVF, 0xFFC00958)    // ToDo: nullsub_1
NHSTUB(GetCurrentAvValue, 0xFFC00958)    // ToDo: nullsub_1
NHSTUB(GetDrive_FreeClusters, 0xFFC00958)    // ToDo: nullsub_1
NHSTUB(GetZoomLensCurrentPoint, 0xFFC00958)    // ToDo: nullsub_1
NHSTUB(GetZoomLensCurrentPosition, 0xFFC00958)    // ToDo: nullsub_1
NHSTUB(Lseek, 0xFFC00958)    // ToDo: nullsub_1
NHSTUB(PT_PlaySound, 0xFFC00958)    // ToDo: nullsub_1
NHSTUB(ReadFastDir, 0xFFC00958)    // ToDo: nullsub_1
NHSTUB(RefreshPhysicalScreen, 0xFFC00958)    // ToDo: nullsub_1
NHSTUB(Remove, 0xFFC00958)    // ToDo: nullsub_1
NHSTUB(TurnOffBackLight, 0xFFC00958)    // ToDo: nullsub_1
NHSTUB(TurnOnBackLight, 0xFFC00958)    // ToDo: nullsub_1
NHSTUB(UIFS_WriteFirmInfoToFile, 0xFFC00958)    // ToDo: nullsub_1
NHSTUB(kbd_pwr_off, 0xFFC00958)    // ToDo: nullsub_1
NHSTUB(kbd_pwr_on, 0xFFC00958)    // ToDo: nullsub_1
NHSTUB(kbd_read_keys, 0xFFC00958)    // ToDo: nullsub_1
NHSTUB(openfastdir, 0xFFC00958)    // ToDo: nullsub_1
NHSTUB(qsort, 0xFFC00958)    // ToDo: nullsub_1
NHSTUB(readfastdir, 0xFFC00958)    // ToDo: nullsub_1
NHSTUB(rename, 0xFFC00958)    // ToDo: nullsub_1

NSTUB(Unmount_FileSystem, 0xFFC00958)    // ToDo: nullsub_1
NSTUB(Mount_FileSystem, 0xFFC00958)    // ToDo: nullsub_1
NSTUB(rewinddir, 0xFFC00958)    // ToDo: nullsub_1
NSTUB(DoAFLock, 0xFFC00958)    // ToDo: nullsub_1
NSTUB(UnlockAF, 0xFFC00958)    // ToDo: nullsub_1
NSTUB(SetScriptMode, 0xFFC00958)    // ToDo: nullsub_1
NSTUB(PostLEDMessage, 0xFFC00958)    // ToDo: nullsub_1
NSTUB(UnsetZoomForMovie, 0xFFC00958)    // ToDo: nullsub_1
NSTUB(SetZoomActuatorSpeedPercent, 0xFFC00958)    // ToDo: nullsub_1
